### ISSUE TITLE
how to coompile the program in  Arm architecture v8

### ISSUE THREAD

**Issue by lstxmu** [stamatak/ExaML#18]
HI， 
I want to test the examl in  Arm architecture v8  cpu,  how to compile the  examl program ?

**Comment by stamatak** [comment]
ExaML is not maintained anymore, please use RAxML-NG https://github.com/amkozlov/raxml-ng
that covers all functionality of ExaML. We have managed to execute RAxML-NG on an ARM architecture, but please repost your question in the RAxML google group and we will answer it there.
