### ISSUE TITLE
libmpi.so.40: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by markusruhsam** [stamatak/ExaML#19]
I installed Examl according to the manual and the` parse-examl` commands are working, however, if I use the `examl `command I get this error `examl: error while loading shared libraries: libmpi.so.40: cannot open shared object file: No such file or directory`. I found this post https://github.com/theislab/cellrank/issues/864 where a similar error was solved using` conda install -c conda-forge openmpi=4.1.2`, however this didn't solve the problem for me as the libraries installed are named slightly different `libmpi_mpifh.so` and `libmpi_mpifh.so.40`. Any help is appreciated!

**Comment by stamatak** [comment]
Examl is not maintained any more, please use RAxML-NG https://github.com/amkozlov/raxml-ng which implements all features of ExaML for supercomputers and is also faster.
